### PR TITLE
feat: Update deed image - MEED-1895 - Meeds-io/MIPs#48

### PR DESCRIPTION
**Pull request by MayTekayaa**
Need to update the image as it has not the same height as other image (meed token) in the white paper page

### CODE REVIEW

**Review by boubaker — COMMENTED** [review]
This same image is used in other pages. When changing the ratio, we will need to make sure that it doesn't affect other pages or duplicate the image, one per page.

**Comment by MayTekayaa** [comment]
> This same image is used in other pages. When changing the ratio, we will need to make sure that it doesn't affect other pages or duplicate the image, one per page.

You are right, it is used in empty deeds assets with mobile and it is ok for me!

**Comment by boubaker** [comment]
@srenault-meeds WDYT ?

**Comment by srenault-meeds** [comment]
> @srenault-meeds WDYT ?

yes go
And we will duplicate them later

**Review by boubaker — APPROVED** [review]

**Pull request merged**
